# -*- coding: utf-8 -*-
"""churn_analiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxMqhTiRmy8gg2Fh2fVZ41Edf0BDZP4Z
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Telco-Customer-Churn.csv')

df.head()

df.tail()

df.info()

df.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))
sns.countplot(x = 'Churn', data = df)
plt.title('Churn Count')
plt.show()

plt.figure(figsize = (8,6))
sns.histplot(x = 'tenure', hue = 'Churn', multiple = 'stack', data = df, bins = 30) # Changed 'Stack' to 'stack'
plt.title('Tenure (Müşteri Süresi) ve Churn İlişkisi')
plt.xlabel('Tenure')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(x='Churn', y='MonthlyCharges', data=df)
plt.title('Aylık Fatura ve Churn İlişkisi')
plt.show()

plt.figure(figsize=(8, 6))
sns.countplot(x='InternetService', hue='Churn', data=df)
plt.title('InternetService ve Churn İlişkisi')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X = pd.get_dummies(df.drop('Churn', axis=1), drop_first=True)
y = df['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

logreg = LogisticRegression(max_iter = 1000)
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Doğruluk: {accuracy}")
print("Karışıklık Matrisi:")
print(conf_matrix)
print("Sınıflandırma Raporu:")
print(class_report)

